### ISSUE TITLE
Unable to verify signature after fresh install

### ISSUE THREAD

**Issue by asurbernardo** [ohmybrew/laravel-shopify#369]
## Expected Behavior

The app validates hmac parameter.

## Current Behavior

I am getting an exception verifying the emac:

## Failure Information

Exception:

```
OhMyBrew\ShopifyApp\Exceptions\SignatureVerificationException
Unable to verify signature.
https://shopysizer.local/?hmac=3ebfb4ce4b8dcd2e104bedcb0b2c864d137b32bc382743854c51cc125c9b6592&locale=es&shop=shopy-sizer.myshopify.com&timestamp=1578411438
```

I am using a docker compose setup: 

```
version: '3.7'
services:

  #PHP Service
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
        - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./:/var/www/html
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        - ./docker/nginx/ssl/:/etc/nginx/ssl/

  #MySQL Service
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: shopysizer
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password

  #Redis Service
  cache:
    image: redis:latest
    container_name: cache
    restart: unless-stopped
    tty: true
```

Current relevant configuration:
```
SHOPIFY_DEBUG=true
SHOPIFY_MANUAL_MIGRATIONS=true
SHOPIFY_MYSHOPIFY_DOMAIN="shopy-sizer.myshopify.com"
SHOPIFY_APP_NAME="Shopy Sizer"
SHOPIFY_API_KEY= xxxxxxx
SHOPIFY_API_SECRET_KEY= xxxxxxx
API_SCOPES="read_orders,read_products,write_script_tags"
AFTER_AUTHENTICATE_JOB="\\App\\Jobs\\AfterAuthenticateJob::class"
AFTER_AUTHENTICATE_JOB_INLINE=true
```

Nginx configuration:
```
server {
    listen 80;
    server_name shopysizer.local;

    return 301 https://shopysizer.local$request_uri;
}


server {
    listen 443 ssl http2;
    server_name shopysizer.local;

    ssl_certificate /etc/nginx/ssl/server.cer;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # Log files for Debug
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Shopify Headers
    add_header X-Frame-Option ALLOWALL;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header p3p 'CP="Not used"';

    # Laravel web root directory
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Nginx Pass requests to PHP-FPM
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

### Steps to Reproduce

I created a repository with my code, you might need to provide api keys and update some configuration variables:

`git clone https://github.com/asurbernardo/laravel-shopify-boilerplate.git`

### Context

* Package Version: 10.2.1
* Laravel Version: 6.10
* PHP Version: 7.4
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker
